name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Link ChromeDriver safely
      run: |
        if [ ! -e /usr/bin/chromedriver ]; then
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        fi

    - name: Run Tests
      run: node tests/loginTests.js

    - name: Upload HTML Test Report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: html-test-report
        path: reports/test_report.html