name: Run Selenium Tests on Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Run Selenium Tests
      run: node tests/loginTests.js

    - name: Upload HTML Test Report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: html-test-report
        path: reports/test_report.html